<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
    <!-- Project properties -->
    <PropertyGroup>
        <AssemblyName>MahApps.Metro.Extension</AssemblyName>
        <Title>MahApps.Metro.Extension</Title>
        <RootNamespace>MahApps.Metro.Extension</RootNamespace>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <DefineConstants>$(DefineConstants);INTERNAL_NULLABLE_ATTRIBUTES</DefineConstants>
    </PropertyGroup>
    <ItemGroup>
      <ProjectReference Include="..\MahApps.Metro\MahApps.Metro.csproj" />
    </ItemGroup> 
</Project>